ARG DENO_VERSION=2.8.1
FROM docker.io/denoland/deno:${DENO_VERSION} AS base
WORKDIR /usr/src/app

FROM base AS install
COPY --parents deno.json deno.lock package.json **/deno.json **/package.json ./

RUN --mount=type=cache,target=/deno-dir \
    deno install --frozen

FROM base AS prerelease
COPY --from=install /usr/src/app/node_modules ./node_modules
COPY . .

RUN cp apps/core/.env.example apps/core/.env
RUN deno task build
