name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run checks
    runs-on: srv-obin-ch_ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Deno
        uses: https://github.com/denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno install

      - name: Check code
        run: deno task check

  end-to-end-tests:
    name: Run end-to-end tests
    runs-on: srv-obin-ch_ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
    env:
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends unzip

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Deno
        uses: https://github.com/denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno install

      - name: Copy environment variables
        run: cp apps/core/.env.example apps/core/.env.local

      - name: Run end-to-end tests
        run: deno task test:e2e
