networks:
  healthcheck:
    name: healthcheck
  proxy:
    name: proxy
    external: true

volumes:
  database:
    driver: local

services:
  core-migrate:
    image: codeberg.org/healthcheck/healthcheck-core:latest
    restart: no
    volumes:
      - database:/database
    environment:
      DATABASE_URL: /database/healthcheck.db
    command: ["migrate"]
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=healthcheck"
    networks:
      - healthcheck

  core:
    image: codeberg.org/healthcheck/healthcheck-core:latest
    restart: unless-stopped
    depends_on:
      core-migrate:
        condition: service_completed_successfully
    volumes:
      - database:/database
    environment:
      DATABASE_URL: /database/healthcheck.db
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: https://www.healthcheck.help
      ORIGIN: https://www.healthcheck.help
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=healthcheck"
      - "traefik.enable=true"
      - "traefik.http.routers.healthcheck-core.rule=Host(`www.healthcheck.help`)"
      - "traefik.http.routers.healthcheck-core.entrypoints=http,https"
      - "traefik.http.routers.healthcheck-core.middlewares=redirect-https"
      - "traefik.http.routers.healthcheck-core.tls=true"
      - "traefik.http.routers.healthcheck-core.tls.certresolver=letsencrypt"
      - "traefik.http.services.healthcheck-core.loadbalancer.server.port=8000"
    networks:
      - proxy
      - healthcheck

  watchtower:
    image: docker.io/nickfedor/watchtower:1.20.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_TOKEN}
      WATCHTOWER_SCOPE: "healthcheck"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_REVIVE_STOPPED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthcheck-watchtower.rule=Host(`watchtower.healthcheck.help`)"
      - "traefik.http.routers.healthcheck-watchtower.entrypoints=https"
      - "traefik.http.routers.healthcheck-watchtower.tls=true"
      - "traefik.http.routers.healthcheck-watchtower.tls.certresolver=letsencrypt"
      - "traefik.http.services.healthcheck-watchtower.loadbalancer.server.port=8080"
    networks:
      - proxy
